# Generated by Django 5.1.9 on 2025-06-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
