# Generated by Django 5.2.3 on 2025-07-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
