# Generated by Django 5.2.3 on 2025-07-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume', models.PositiveIntegerField()),
                ('abv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vintage', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='common.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='common.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='common.country')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='shop.product')),
            ],
        ),
    ]
