# Generated by Django 5.1.11 on 2025-06-30 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='grand_total',
        ),
    ]
